version: '3.7'

services:

  omnomnom:
    command: yarn run start
    container_name: "omnomnom"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/usr/src/app/src
      - ./public:/usr/src/app/public
    ports:
      - "3000:3000"
    user: "1000"
    #environment:
      #CHOKIDAR_USEPOLLING: "true"
    stdin_open: true # docker run -i
    # tty: true        # docker run -t
    networks:
      - public
    restart: on-failure

networks:
  public:
    name: public
